# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  appName: 'sony-rcp-server'
  buildConfiguration: 'Release'

steps:
- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '/3d77afcb-a6e8-4ae6-87cb-78ceee997060'
    view: '72b44465-cc04-46c3-89b4-a4859ca0bf8a'
    definition: '6cf844b3-9456-4dd2-b15c-6cacfe4417ca'
    version: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '/3d77afcb-a6e8-4ae6-87cb-78ceee997060'
    view: '72b44465-cc04-46c3-89b4-a4859ca0bf8a'
    definition: 'fa6d9be1-0b64-4163-88d0-322b0d5fdf64'
    version: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'


- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
