# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  appName: 'sony-rcp-server'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '3d77afcb-a6e8-4ae6-87cb-78ceee997060'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: --configuration $(buildConfiguration)
    projects: '**/*.csproj'
    
